---
title: "Projects"
listing:
  - id: projects
    contents: "projects"
    sort:
      - "title asc"
    type: default
    categories: true
    sort-ui: false
    filter-ui: false
page-layout: full
title-block-banner: false
---


::: callout-tip
### Submitting Quarto documents to CoursePlus

Some of you might choose to use Quarto for making your HTML project files instead of Rmarkdown. If so, keep in mind that Quarto will create a directory that has to be shared along with the HTML file ^[RMarkdown generates self-contained HTML files whereas Quarto does not.]. 

In this case, open the HTML file on your browser, then create a PDF by printing the HTML file to PDF from your browser. You can then upload the PDF file to CoursePlus. Keep in mind that long lines of code might get cut off when printing to PDF, so you might want to adjust the width of your code chunks in your Quarto document accordingly.

Previously I had stated that you could submit a ZIP file, but we found this to add unnecessary complexity to the submission process. So please submit a PDF file instead for Quarto documents.

Deprecated instructions:

> That is, you will have to make a ZIP file that contains both the (A) HTML file made with Quarto, and (B) the *_quarto_files directory that Quarto also made. Then upload the ZIP file to CoursePlus.
> 
> Taking <https://github.com/lcolladotor/StatComputing_ProjectDemo> as an example, the ZIP file would have to contain:
> 
> * The HTML file <https://github.com/lcolladotor/StatComputing_ProjectDemo/blob/gh-pages/2025-09-02_demo_quarto.html>
> * The `"*_quarto_files"` directory <https://github.com/lcolladotor/StatComputing_ProjectDemo/tree/gh-pages/2025-09-02_demo_quarto_files>
:::

::: callout-important
### Verifying your project submission

Download your own project submission from CoursePlus to verify that it looks as you intended. To do so, I recommend downloading your submission to your `~/Desktop` or `~/Downloads` directory (one that is separate from where you did the initial work). Then open the HTML file on your browser to verify that it does indeed look as you intended (or PDF file for Quarto documents). That is, verify that the HTML file has:

* code chunks with the code you evaluated
* figures that were generated by your code
* results that were generated by your code
* text that you wrote describing the results

:::

::: callout-note
### Can I use LLMs for my projects?

Can I use LLMs (e.g., ChatGPT, GitHub Copilot, etc.) for my projects? The answer is **yes**. Remember to cite all tools that you used! You can do so just before including your R session information at the end of your document.

I recommend that you start by configuring your `RStudio IDE` or `Positron` to use GitHub Copilot as discussed in the [01 - Welcome! lecture](posts/01-welcome/#how-to-apply-for-github-education-and-configure-github-copilot). That might be enough for most of you. However, if you want to interact with LLMs via chat windows, I recommend that you use `chattr` and `ellmer` so you can interact with LLMs directly from R IDE environments. See the details about this on the [14 - R Nuts and Bolts lecture](posts/14-r-nuts-and-bolts/#interacting-with-llms-in-rstudio-ide-positron).

:::