---
title: "Schedule"
description: |
 Schedule and course materials for Statistical Computing (JHSPH Biostatistics 140.776 Fall 2023).
tbl-colwidths: [15,10, 55, 25]
engine: knitr
---

## Schedule and course materials

For Qmd files (markdown document with [Quarto](https://quarto.org/docs/authoring/markdown-basics.html) cross-language executable code), go to the [course GitHub repository](https://github.com/lcolladotor/jhustatcomputing2023) and navigate the directories, or best of all to `git clone` the repo and navigate within `RStudio`.

Check <https://github.com/lcolladotor/biostat776classnotes> for Leo's live class notes.

::: column-page
| Week         | Lectures / due dates                | Topics                                                                                                                                                                                                                                                                                                                                                                                                            | Projects                                                                                                                                                                                                                                                                                      |     |
|---------------|---------------|---------------|---------------|---------------|
| **Module 1** |                                     | **Statistical and computational tools for scientific and reproducible research**                                                                                                                                                                                                                                                                                                                                  |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 1       | Lecture 1 (**Leo will be remote!**) | `r emojifont::emoji('wave')` Course introduction \[[html](posts/01-welcome/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/01-welcome/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/01-welcome/index.R)\]                                                                                                                      | `r emojifont::emoji('palm_tree')` Project 0 \[[html](projects/project-0/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-0/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-0/index.R)\] |     |
|              |                                     | `r emojifont::emoji('woman_technologist')` Introduction to R and RStudio \[[html](posts/02-introduction-to-r-and-rstudio/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/02-introduction-to-r-and-rstudio/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/02-introduction-to-r-and-rstudio/index.R)\]                            |                                                                                                                                                                                                                                                                                               |     |
|              |                                     | `r emojifont::emoji('octopus')` Introduction to git/GitHub \[[html](posts/03-introduction-to-gitgithub/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/03-introduction-to-gitgithub/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/03-introduction-to-gitgithub/index.R)\]                                                      |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 2 (**Leo will be remote!**) | `r emojifont::emoji('microscope')` Reproducible Research \[[html](posts/04-reproducible-research/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/04-reproducible-research/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/04-reproducible-research/index.R)\]                                                                    |                                                                                                                                                                                                                                                                                               |     |
|              |                                     | `r emojifont::emoji('eyeglasses')` Literate programming \[[html](posts/05-literate-programming/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/05-literate-programming/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/05-literate-programming/index.R)\]                                                                        |                                                                                                                                                                                                                                                                                               |     |
|              |                                     | `r emojifont::emoji('cool')` Reference management \[[html](posts/06-reference-management/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/06-reference-management/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/06-reference-management/index.R)\]                                                                              |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| **Module 2** |                                     | **Data analysis in R**                                                                                                                                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 2       | Lecture 3                           | `r emojifont::emoji('eyes')` Reading and writing data \[[html](posts/07-reading-and-writing-data/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/07-reading-and-writing-data/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/07-reading-and-writing-data/index.R)\]                                                              | `r emojifont::emoji('palm_tree')` Project 1 \[[html](projects/project-1/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-1/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-1/index.R)\] |     |
|              |                                     | `r emojifont::emoji('scissors')` Managing data frames with Tidyverse \[[html](posts/08-managing-data-frames-with-tidyverse/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/08-managing-data-frames-with-tidyverse/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/08-managing-data-frames-with-tidyverse/index.R)\]              |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 4                           | `r emojifont::emoji('heart_eyes_cat')` Tidy data and the Tidyverse \[[html](posts/09-tidy-data-and-the-tidyverse/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/09-tidy-data-and-the-tidyverse/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/09-tidy-data-and-the-tidyverse/index.R)\]                                        | `r emojifont::emoji('fallen_leaf')` Project 0 due                                                                                                                                                                                                                                             |     |
|              |                                     | `r emojifont::emoji('handshake')` Joining data in R: Basics \[[html](posts/10-joining-data-in-r/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/10-joining-data-in-r/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/10-joining-data-in-r/index.R)\]                                                                             |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| **Module 3** |                                     | **Data visualizations R**                                                                                                                                                                                                                                                                                                                                                                                         |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 3       | Lecture 5                           | `r emojifont::emoji('bar_chart')` Plotting systems in R \[[html](posts/11-plotting-systems/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/11-plotting-systems/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/11-plotting-systems/index.R)\]                                                                                    |                                                                                                                                                                                                                                                                                               |     |
|              |                                     | `r emojifont::emoji('bar_chart')` The ggplot2 plotting system: qplot() \[[html](posts/12-ggplot2-plotting-system-part-1/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/12-ggplot2-plotting-system-part-1/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/12-ggplot2-plotting-system-part-1/index.R)\]                           |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 6                           | `r emojifont::emoji('bar_chart')` The ggplot2 plotting system: ggplot() \[[html](posts/13-ggplot2-plotting-system-part-2/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/13-ggplot2-plotting-system-part-2/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/13-ggplot2-plotting-system-part-2/index.R)\]                          | `r emojifont::emoji('palm_tree')` Project 2 \[[html](projects/project-2/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-2/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-2/index.R)\] |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Sept 17                             |                                                                                                                                                                                                                                                                                                                                                                                                                   | `r emojifont::emoji('fallen_leaf')` Project 1 due                                                                                                                                                                                                                                             |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| **Module 4** |                                     | **Nuts and bolts of R**                                                                                                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 4       | Lecture 7                           | `r emojifont::emoji('nut_and_bolt')` R Nuts and Bolts \[[html](posts/14-r-nuts-and-bolts/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/14-r-nuts-and-bolts/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/14-r-nuts-and-bolts/index.R)\]                                                                                      |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 8                           | `r emojifont::emoji('nut_and_bolt')` Control structures in R \[[html](posts/15-control-structures/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/15-control-structures/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/15-control-structures/index.R)\]                                                                         |                                                                                                                                                                                                                                                                                               |     |
|              |                                     | `r emojifont::emoji('nut_and_bolt')` Functions in R \[[html](posts/16-functions/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/16-functions/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/16-functions/index.R)\]                                                                                                             |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 5       | Lecture 9                           | `r emojifont::emoji('nut_and_bolt')` Loop functions \[[html](posts/17-loop-functions/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/17-loop-functions/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/17-loop-functions/index.R)\]                                                                                              |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 10                          | `r emojifont::emoji('bug')` Debugging code in R \[[html](posts/18-debugging-r-code/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/18-debugging-r-code/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/18-debugging-r-code/index.R)\]                                                                                            |                                                                                                                                                                                                                                                                                               |     |
|              |                                     | `r emojifont::emoji('bug')` Error handling code in R \[[html](posts/19-error-handling-and-generation/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/19-error-handling-and-generation/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/19-error-handling-and-generation/index.R)\]                                                |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Oct 1                               |                                                                                                                                                                                                                                                                                                                                                                                                                   | `r emojifont::emoji('fallen_leaf')` Project 2 due                                                                                                                                                                                                                                             |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| **Module 5** |                                     | **Special data types in R**                                                                                                                                                                                                                                                                                                                                                                                       |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 6       | Lecture 11                          | `r emojifont::emoji('calendar')` Working with dates and times \[[html](posts/20-working-with-dates-and-times/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/20-working-with-dates-and-times/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/20-working-with-dates-and-times/index.R)\]                                          | `r emojifont::emoji('palm_tree')` Project 3 \[[html](projects/project-3/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-3/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/projects/project-3/index.R)\] |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 12                          | `r emojifont::emoji('sparkles')` Regular expressions \[[html](posts/21-regular-expressions/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/21-regular-expressions/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/21-regular-expressions/index.R)\]                                                                              |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 7       | Lecture 13                          | `r emojifont::emoji('cat')` Working with factors \[[html](posts/22-working-with-factors/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/22-working-with-factors/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/22-working-with-factors/index.R)\]                                                                               |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 14                          | `r emojifont::emoji('calendar')` Working with text data and sentiment analysis \[[html](posts/23-working-with-text-sentiment-analysis/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/23-working-with-text-sentiment-analysis/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/23-working-with-text-sentiment-analysis/index.R)\] |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| **Module 6** |                                     | **Best practices for working with data and other languages**                                                                                                                                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
| Week 8       | Lecture 15                          | `r emojifont::emoji('cloud')` Best practices for data analysies \[[html](posts/24-best-practices-data-analyses/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/24-best-practices-data-analyses/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/24-best-practices-data-analyses/index.R)\]                                        |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Lecture 16                          | `r emojifont::emoji('snake')` Leveraging Python within R \[[html](posts/25-python-for-r-users/index.html)\] \[[Qmd](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/25-python-for-r-users/index.qmd)\] \[[R](https://github.com/lcolladotor/jhustatcomputing2023/blob/main/posts/25-python-for-r-users/index.R)\]                                                                             |                                                                                                                                                                                                                                                                                               |     |
|              |                                     |                                                                                                                                                                                                                                                                                                                                                                                                                   |                                                                                                                                                                                                                                                                                               |     |
|              | Oct 23                              |                                                                                                                                                                                                                                                                                                                                                                                                                   | `r emojifont::emoji('fallen_leaf')` Project 3 due                                                                                                                                                                                                                                             |     |
:::
